load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "lat_based_stanley_controller_conf_proto",
    srcs = ["lat_based_stanley_controller_conf.proto"],
    deps=[],
)

apollo_package()